<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>

    <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bruno Sales</Authors>
    <Description>A .NET library for interacting with the Assuan protocol.</Description>
    <Copyright>Copyright (c) $([System.DateTime]::Now.Year) Bruno Sales &lt;me@baliestri.dev&gt;</Copyright>
    <PackageId>AssuanLibrary.Extensions.DependencyInjection</PackageId>
    <PackageProjectUrl>https://github.com/baliestri/assuan-library</PackageProjectUrl>
    <PackageTags>assuan; gpg; gpgme; gnupg; dependency-injection; di; extensions; microsoft-di</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <RepositoryUrl>https://github.com/baliestri/assuan-library</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Company>baliestri</Company>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" Condition="Exists('README.md')" />
    <None Include="..\..\LICENSE.md" Pack="true" PackagePath="\"
      Condition="Exists('..\..\LICENSE.md')" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssuanLibrary\AssuanLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
