<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>

    <PolyArgumentExceptions>true</PolyArgumentExceptions>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bruno Sales</Authors>
    <Description>A .NET library for interacting with the Assuan protocol.</Description>
    <Copyright>Copyright (c) $([System.DateTime]::Now.Year) Bruno Sales &lt;me@baliestri.dev&gt;</Copyright>
    <PackageId>AssuanLibrary</PackageId>
    <PackageProjectUrl>https://github.com/baliestri/assuan-library</PackageProjectUrl>
    <PackageTags>assuan; gpg; gpgme; gnupg</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <RepositoryUrl>https://github.com/baliestri/assuan-library</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Company>baliestri</Company>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md" Pack="true" PackagePath="\" Condition="Exists('..\LICENSE.md')" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AssuanLibrary.AssuanPredefined" Static="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>

</Project>
